ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

# COPY zh-TW.json /usr/share/kibana/node_modules/x-pack/plugins/translations/translations/zh-TW.json

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
